---
group_chat_id: 355136767

skip_keywords:
  - work-in-progress
  - do-not-merge

developers:
  - username: fantom0005
    tg_chat_id: 355136767
    timetable:
      days:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
      started_at: "09:00:00"
      ended_at: "17:00:00"

  - username: sokdestroy
    tg_chat_id: 355136767
    timetable:
      days:
        - Monday
      started_at: "12:00:00"
      ended_at: "20:00:00"

  - username: aovlexus
    tg_chat_id: 355136767
    timetable:
      days:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
      started_at: "09:00:00"
      ended_at: "17:00:00"

  - username: lexusimprovado
    tg_chat_id: 355136767
    timetable:
      days:
        - Monday
      started_at: "12:00:00"
      ended_at: "20:00:00"

  - username: VladimirZaytsev
    tg_chat_id: 355136767
    timetable:
      days:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
      started_at: "09:00:00"
      ended_at: "17:00:00"

  - username: vlmihnevich
    tg_chat_id: 355136767
    timetable:
      days:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
      started_at: "09:00:00"
      ended_at: "17:00:00"

  - username: nilya
    tg_chat_id: 355136767
    timetable:
      days:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
      started_at: "09:00:00"
      ended_at: "17:00:00"

  - username: 123phg
    tg_chat_id: 355136767
    timetable:
      days:
        - Monday
      started_at: "12:00:00"
      ended_at: "20:00:00"

  - username: denex
    tg_chat_id: 355136767
    timetable:
      days:
        - Monday
      started_at: "12:00:00"
      ended_at: "20:00:00"

  - username: oev81
    tg_chat_id: 355136767
    timetable:
      days:
        - Monday
      started_at: "01:00:00"
      ended_at: "01:10:00"

  - username: figonet
    tg_chat_id: 355136767
    timetable:
      days:
        - Monday
      started_at: "01:00:00"
      ended_at: "01:10:00"

  - username: HagasSaan
    tg_chat_id: 355136767
    timetable:
      days:
        - Monday
      started_at: "01:00:00"
      ended_at: "01:10:00"

